### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by 8databit** [andylamp/BPlusTree#1]
I just wanted to say that i had a look at your code and i wanted to thank you! 
Good job you did there, cost you some time for sure. I love it. Couldnt help myself but reading everything. (Docs n sht)

Anyways 1 issue though... the randomaccesfile object sucks for writing xD. The seeks cost to much 2! But i fixed that by just caching the nodes in a linkedhashmap for N seconds, untill another thread cleans it up if its out of time.

Didn't enjoy a project this much in a while :3

**Comment by andylamp** [comment]
hi - thanks for the kind words. Since this is not a technical issue am closing it :).
