### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by asad-awadia** [andylamp/BPlusTree#10]
hey @andylamp great work here!

Is this tree thread safe?

**Comment by andylamp** [comment]
hey, thanks for the good words! Not sure what you mean exactly by thread-safe; the code does not support multiple threads currently.

However, as is, if you do slight tweaks you can perform concurrent reads without an issue, but if you want to perform mixed workloads that include writing and reads at the same query batch then, no.

Hope this helps.

**Comment by asad-awadia** [comment]
ok got  it! thanks!
