### ISSUE TITLE
call out limitations of the library in README

### ISSUE THREAD

**Issue by siddhsql** [andylamp/BPlusTree#14]
Thanks for this library. Just a note that you should also call out the limitations of this library. e.g., the library truncates values stored into the b+ tree.

```
private String conditionString(String s) {
        if(s == null) {
            s = " ";
            //System.out.println("Cannot have a null string");
        }

        if(s.length() > conf.getEntrySize()) {
            System.out.println("Satellite length can't exceed " +
                    conf.getEntrySize() + " trimming...");
            s = s.substring(0, conf.getEntrySize());
        } else if(s.length() < conf.getEntrySize()) {
            //System.out.println("Satellite length can't be less than" +
            //        conf.getEntrySize() + ", adding whitespaces to make up");
            int add = conf.getEntrySize() - s.length();
            for(int i = 0; i < add; i++) {s = s + " ";}
        }
        return(s);
    }
```

as a user I feel better if I know the limitations upfront vs. discovering them by surprise which makes me feel cheated.

**Comment by andylamp** [comment]
Hey, thanks for the message - I think this is clearly stated in the implementation and in the output messages you see. 

However, I will add it to the readme but you _can_ adjust the entry size within the [configuration](https://github.com/andylamp/BPlusTree/blob/master/src/main/java/ds/bplus/bptree/BPlusConfiguration.java#L15)... Thus I think your point is a bit invalid. It is certainly not meant to mislead people.

Finally, the language used in your comment is inflammatory and as an open source maintainer myself, I am not OK with such comments. The software comes without any support and was developed out of good will, use it with caution - it is even stated within the license.

Hope this helps.

**Comment by siddhsql** [comment]
Hi Andy, I apologize. no offense was intended. I tried to explain the
reasoning in my comment.

**Comment by andylamp** [comment]
I think using "cheated" is rather strong language especially given the context and the way it was mentioned. In any case, I have changed the readme to clearly indicate this along with where you can tweak the parameter to suit your desired datatype sizes.

Have a good day.
