### ISSUE TITLE
Licensing for C# port

### ISSUE THREAD

**Issue by smbogan** [andylamp/BPlusTree#7]
I'm looking to port this to C# for use in a commercial product.  I'm happy to release the ported code, but I'm curious if you would mind allowing me to release it with the MIT license?  Or possibly also to consider licensing this code as MIT?  Unfortunately, the GPL is an unpopular set of licenses with our legal department.

**Comment by andylamp** [comment]
Hi there - thanks for letting me know; would it be better if I licensed with LGPL instead?

**Comment by smbogan** [comment]
Thanks for the response.  I'm not a lawyer, but my understanding is that typically, the MIT, Apache 2.0, or other BSD-style licenses are safer from a legal perspective as there's no concern of ambiguity about what is or is not a derivative work, and they don't impose any potentially onerous requirements on distribution.  With LGPL it's potentially very easy to accidentally create what might be considered a derivative work by, for example, inheriting from a class in an LGPL library.

That said, I appreciate that this work belongs to you, and you own the copyright to distribute under any license you want.  If you're willing to release it under the LGPL, it might limit what we can all do with it, but I still think that I would likely be able to use it for the use case I have in mind currently.  In any event, I will happily release on GitHub the C# port under the most permissive license you're willing to allow, and if you would like, when the code is uploaded, I can provide you a link for anyone interested in the port.

**Comment by andylamp** [comment]
ah, cool - let me get a brush up on Apache 2.0 based licenses and get back to you! Generally speaking I want the sources and direct ports/enhancements of this library to be open source for all to see.

PS: sorry for the late responses but schedule is a bit hectic these days...

**Comment by andylamp** [comment]
getting back to this - I think releasing it under Apache 2.0 license should work; thus, I think this should satisfy all of your requirements while maintaining the spirit of the project.

**Comment by smbogan** [comment]
Thank you, I appreciate it.  I'll release the C# port of the code under the same license.

**Comment by andylamp** [comment]
am closing this issue as I've updated the license. Feel free to reopen if there is any other concern regarding the licensing.
