### ISSUE TITLE
GPL or Apache License 2.0?

### ISSUE THREAD

**Issue by jixuan1989** [andylamp/BPlusTree#8]
Hi,
I am interested in this implementation.  
I'd like to know which License does this library use? The readme.md says it is GPLv3 while it is Apache License 2.0 on the github repo.
![image](https://user-images.githubusercontent.com/1021782/70497010-a8b32a80-1b4c-11ea-8ddd-992b80e3e135.png)

According to https://www.apache.org/legal/resolved.html#category-x, if you use GPLv3, then for a project which use Apache 2.0 license, the project can not use your library because they are not compatible..

For example, if Apache Cassandra/ Apache IoTDB databases want to use this implemention, they are not allowed.

**Comment by andylamp** [comment]
ah - yes I see what you mean; this is an oversight when I changed the license as per [this](issue) and I forgot to update the README itself.

That discrepancy should be fixed now - feel free to reopen this issue if you think your issue still persists.
